#!/bin/bash

mkdir -p frontera_specfiles
for s in *.spec ; do
    cat $s \
	> frontera_specfiles/$s
done

cat install.sh \
| sed -e 's/COMPILERS/i191 i231 g91 g132/' -e 's/MPI/-j19_9/' \
> frontera_specfiles/install.sh

cd frontera_specfiles
chmod +x install.sh
if [ ! -f README ] ; then
cat <<EOF >README
These files are generated by the "frontera.sh" script
one level lower.
EOF
fi

