#!/bin/bash

mkdir -p horizon_specfiles
for s in *.spec ; do
    cat $s \
	| sed \
	    -e 's/frontera/horizon/' \
	    -e 's/PETSCCUDAFLAG/-c/' \
	    -e '/noreloc/s/name-defines.*$/name-defines-cuda-noreloc-home1.inc/' \
	    -e '/module load python3/d' \
	    -e '/^FRONTERA/d' \
	    -e '/^LS6/d' \
	    -e '/^STAMPEDE3/d' \
	    -e 's/GCC/14/' \
	    -e 's/rpmtng/RPMtheNextGeneration/' \
	> horizon_specfiles/$s
done

cat install.sh \
    | sed -e 's/frontera/horizon/' \
	  -e 's/COMPILERS/g161,o5_0_10 n265,o5_0_10/' \
	  -e 's/x86_64/aarch64/' \
    > horizon_specfiles/install.sh

# vista: n249,o5_05,k126 n253,o5_07,k128 n255,o5_08,k128 g142,o5_07,k126 g151,o5_09,k128

cd horizon_specfiles
chmod +x install.sh
# cat <<EOF >README
# These files are generated by the "horizon.sh" script
# one level lower.
# EOF
