#!/bin/bash

mkdir -p ls6_specfiles
for s in *.spec ; do
    cat $s \
	| sed \
	    -e 's/frontera/ls6/' \
	    -e '/noreloc/s/name-defines.*$/name-defines-noreloc-scratch.inc/' \
	> ls6_specfiles/$s
done

cat install.sh \
| sed -e 's/frontera/ls6/' -e 's/COMPILERS/i240,j21_11 i19,j19_0 g112,j19_0 g132,j19_0/' \
> ls6_specfiles/install.sh

cd ls6_specfiles
chmod +x install.sh
# cat <<EOF >README
# These files are generated by the "ls6.sh" script
# one level lower.
# EOF
