#!/bin/bash

mkdir -p stampede3_specfiles
for s in *.spec ; do
    cat $s \
	| sed \
	    -e 's/frontera/stampede3/' \
	    -e 's/PETSCCUDAFLAG//' \
	    -e '/noreloc/s/name-defines.*$/name-defines-noreloc-home1.inc/' \
	    -e '/module load python3/d' \
	    -e '/^FRONTERA/d' \
	    -e '/^LS6/d' \
	    -e 's/GCCDEF/13/' \
	    -e 's/GCCMIN/13/' \
	    -e 's/CMAKEMIN/3.28/' \
	> stampede3_specfiles/$s
done

cat install.sh \
    | sed -e 's/frontera/stampede3/' \
	  -e 's/COMPILERS/i240,j21_11 i251,j21_15 g132,j21_9 g151,j21_15 n253,o5_07/' \
    > stampede3_specfiles/install.sh

cd stampede3_specfiles
chmod +x install.sh
# cat <<EOF >README
# These files are generated by the "stampede3.sh" script
# one level lower.
# EOF
