#!/bin/bash

mkdir -p stampede3_specfiles
fi
for s in *.spec ; do
    cat $s \
	| sed -e 's/frontera/stampede3/' -e '/noreloc/s/name-defines.*$/name-defines-noreloc.inc/' \
	> stampede3_specfiles/$s
done

cat install.sh \
| sed -e 's/fontera/stampede3/' -e 's/COMPILERS/i240 g132/' -e 's/MPI/-j21_11/' \
> stampede3_specfiles/install.sh

cd stampede3_specfiles
chmod +x install.sh
cat <<EOF >README
These files are generated by the "stampede3.sh" script
one level lower.
EOF
