#!/bin/bash

mkdir -p stampede3_specfiles
for s in *.spec ; do
    cat $s \
	| sed \
	    -e 's/frontera/stampede3/' \
	    -e '/noreloc/s/name-defines.*$/name-defines-noreloc.inc/' \
	    -e '/module load python3/d' \
	> stampede3_specfiles/$s
done

cat install.sh \
| sed -e 's/frontera/stampede3/' -e 's/COMPILERS/i240,j21_11 g132,j21_11/' \
> stampede3_specfiles/install.sh

cd stampede3_specfiles
chmod +x install.sh
# cat <<EOF >README
# These files are generated by the "stampede3.sh" script
# one level lower.
# EOF
