#!/bin/bash

mkdir -p vista_specfiles
for s in *.spec ; do
    cat $s \
	| sed \
	    -e 's/frontera/vista/' \
	    -e 's/PETSCCUDAFLAG/-c/' \
	    -e '/noreloc/s/name-defines.*$/name-defines-cuda-noreloc-home1.inc/' \
	    -e '/module load python3/d' \
	    -e '/FRONTERA/d' \
	> vista_specfiles/$s
done

cat install.sh \
    | sed -e 's/frontera/vista/' \
	  -e 's/COMPILERS/n249,o5_05,k126 n253,o5_07,k128 g142,o5_07,k126/' \
	  -e 's/x86_64/aarch64/' \
    > vista_specfiles/install.sh

cd vista_specfiles
chmod +x install.sh
# cat <<EOF >README
# These files are generated by the "vista.sh" script
# one level lower.
# EOF
